services:

  couchdb:
    image: couchdb:3.5
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5984
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -u \"$COUCHDB_USER:$COUCHDB_PASSWORD\" http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian-livesync.rule=Host(`${COUCHDB_SETUP_URI_HOSTNAME}`)"
      - "traefik.http.routers.obsidian-livesync.entrypoints=websecure"
      - "traefik.http.routers.obsidian-livesync.service=obsidian-livesync"
      - "traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984"
      - "traefik.http.routers.obsidian-livesync.tls=true"
      - "traefik.http.routers.obsidian-livesync.tls.certresolver=tw"
      - "traefik.http.routers.obsidian-livesync.middlewares=obsidiancors"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"

  init-db:
    image: curlimages/curl:8.15.0
    restart: no
    depends_on:
      couchdb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  traefik:
    image: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.tw.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.tw.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.tw.acme.dnschallenge=true"
      - "--certificatesresolvers.tw.acme.dnschallenge.provider=timewebcloud"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - traefik-data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  couchdb-data:
  traefik-data:
