services:

  couchdb:
    image: couchdb:3.5
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5984
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 10

  init-db:
    image: curlimages/curl:8.15.0
    restart: no
    depends_on:
      couchdb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  nginx:
    image: jonasal/nginx-certbot:5.2.1-nginx1.27.0-alpine
    restart: unless-stopped
    depends_on:
      couchdb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    ports:
      - "80:80"
      - "443:443"

volumes:
  couchdb-data:
  nginx_secrets:
